// ============================================================
// ARTAKITA — BAHASA INDONESIA
// ============================================================

export const APP_NAME    = "ArtaKita";
export const APP_TAGLINE = "Artaku Artamu";
export const APP_VERSION = "2.0.0";
export const APP_AUTHOR  = "MIH";

export const NAV = {
  HOME:    "Beranda",
  STATS:   "Statistik",
  FINANCE: "Keuangan",
  MORE:    "Lainnya",
};

export const HOME = {
  TOTAL_BALANCE:  "Total Saldo",
  CIRCULATION:    "Sirkulasi Berjalan",
  INCOME:         "Pemasukan",
  EXPENSE:        "Pengeluaran",
  ACTIVITY_LOG:   "Log Aktivitas",
  SEARCH_HINT:    "Cari transaksi...",
  EMPTY:          "Belum ada transaksi",
  LOAD_MORE:      "Muat Lebih Banyak",
  LOADING:        "Memuat...",
  FILTER_TODAY:   "Hari Ini",
  FILTER_WEEK:    "7 Hari",
  FILTER_MONTH:   "Bulan Ini",
  FILTER_CUSTOM:  "Pilih Tanggal",
  ALL_CATEGORIES: "Semua",
  DATE_FROM:      "Dari Tanggal",
  DATE_TO:        "Sampai Tanggal",
  OFFLINE_MSG:    "Offline — transaksi akan disinkronkan saat online",
  SYNCING_MSG:    (n) => `Menyinkronkan ${n} transaksi...`,
  PENDING_MSG:    (n) => `${n} transaksi menunggu sinkronisasi`,
};

export const WALLET = {
  TITLE:       "Dompet",
  PERSONAL:    "Rekening Pribadi",
  SHARED_WITH: (u) => `Dibagikan ke @${u}`,
  SHARED_BY:   (u) => `Dibagikan oleh @${u}`,
  ACTIVE:      "Aktif",
  ADD_NEW:     "Tambah Rekening Baru",
  NAME_LABEL:  "Nama Rekening",
  NAME_HINT:   "Cth: BCA Pribadi",
  SAVE:        "Simpan",
  OPEN:        "Buka Rekening",
  SETUP_TITLE: "Buat Rekening Pertama",
  SETUP_DESC:  "Selamat datang! Buat rekening untuk mulai mencatat keuangan kamu.",
  CREATE:      "Buat Rekening",
};

export const STATS = {
  TITLE:          "Statistik",
  TAB_EXPENSE:    "Pengeluaran",
  TAB_ALLOCATION: "Alokasi",
  TOTAL_EXPENSE:  "Total Pengeluaran",
  TOTAL_INCOME:   "Pemasukan",
  CATEGORY_DETAIL:"Rincian Kategori",
  ALLOCATION:     "Alokasi per Kategori",
  SET_LIMIT:      "Atur Batas",
  LIMIT_LABEL:    "Batas Anggaran",
  LIMIT_HINT:     "Cth: 500k, 1jt",
  DELETE_LIMIT:   "Hapus Batas",
  SAVE_LIMIT:     "Simpan Batas",
  USED_THIS_MONTH:"Terpakai bulan ini",
  CURRENT_LIMIT:  "Batas saat ini",
  REMAINING:      "Sisa",
  OVER_LIMIT:     "Melebihi Batas!",
  NOT_SET:        "Belum diatur",
  WARNING_OVER:   "Total alokasi melebihi saldo. Sesuaikan batas anggaran.",
  AFTER_ALLOC:    "Sisa saldo setelah alokasi",
  HEALTH_TITLE:   "Status Keuangan",
  NO_DATA:        "Belum ada data bulan ini",
  GRADE: {
    A: "Sangat Sehat! Surplus kas Anda aman.",
    B: "Bagus. Keuangan Anda cukup stabil bulan ini.",
    C: "Waspada. Kurangi pengeluaran yang tidak perlu.",
    D: "Bahaya! Pengeluaran nyaris melebihi pemasukan.",
    F: "Minus! Belum ada pemasukan yang tercatat.",
    "-": "Belum ada transaksi bulan ini.",
  },
};

export const FINANCE = {
  TITLE:          "Keuangan",
  DEBTS:          "Hutang & Piutang",
  RECURRING:      "Transaksi Rutin",
  ASSETS:         "Manajemen Aset",
  CATEGORIES:     "Kategori",
  SAVINGS:        "Celengan & Target",
  DEBTS_SUB:      "Catat & kelola hutang piutang",
  RECURRING_SUB:  "Jadwal transaksi berulang",
  ASSETS_SUB:     "Inventaris barang & properti",
  CATEGORIES_SUB: "Kelola kategori transaksi",
  SAVINGS_SUB:    "Tabungan & target impian",
};

export const DEBT = {
  TITLE:        "Hutang & Piutang",
  TAB_DEBT:     "Hutang",
  TAB_RECEIVE:  "Piutang",
  TAB_PAID:     "Lunas",
  TOTAL_DEBT:   "Total Hutang",
  TOTAL_REC:    "Total Piutang",
  SORT:         "Urutkan",
  SORT_NOMINAL: "Nominal Terbesar",
  SORT_PERCENT: "Persentase Terbayar",
  SORT_DUEDATE: "Jatuh Tempo Terdekat",
  ADD_NEW:      "Catat Baru",
  PERSON_NAME:  "Nama",
  PERSON_HINT:  "Cth: Budi, Siti",
  NOMINAL:      "Nominal",
  NOMINAL_HINT: "Cth: 500k, 1jt",
  DUE_DATE:     "Jatuh Tempo",
  PAY_DEBT:     "Bayar Hutang",
  RECEIVE:      "Terima Piutang",
  CANCEL:       "Batal",
  EDIT:         "Ubah",
  DELETE:       "Hapus",
  SAVE:         "Simpan",
  PAID_BADGE:   "Lunas",
  PAID_PERCENT: "Terbayar",
  REMAINING:    "Sisa",
  PAYMENT_HISTORY: "Riwayat Pembayaran",
  EMPTY_DEBT:   "Belum ada catatan hutang",
  EMPTY_REC:    "Belum ada catatan piutang",
  EMPTY_PAID:   "Belum ada yang lunas",
  SAVE_DEBT:    "Simpan Hutang",
  SAVE_REC:     "Simpan Piutang",
  WALLET_BALANCE: "Saldo dompet",
  EXCEED_DEBT:  (v) => `Melebihi sisa hutang: Rp ${v}`,
  EXCEED_BAL:   (v) => `Saldo tidak cukup! Saldo: Rp ${v}`,
  EXCEED_ZERO:  "Nominal harus lebih dari 0",
};

export const ASSET = {
  TITLE:        "Manajemen Aset",
  TOTAL_ASSETS: "Total Aset",
  TOTAL_VALUE:  "Estimasi Nilai",
  ITEMS:        "barang tercatat",
  ADD_NEW:      "Tambah Aset",
  EDIT:         "Ubah Aset",
  NAME_LABEL:   "Nama Barang",
  NAME_HINT:    "Cth: Laptop Dell XPS",
  STORE_LABEL:  "Nama Toko",
  STORE_HINT:   "Tokopedia, iBox...",
  DATE_LABEL:   "Tanggal Pembelian",
  PRICE_LABEL:  "Harga Beli",
  PRICE_HINT:   "Cth: 5jt, 500k",
  CONDITION:    "Kondisi",
  NOTES_LABEL:  "Catatan",
  NOTES_HINT:   "Serial number, garansi...",
  PHOTO:        "Foto Aset",
  CAMERA:       "Kamera / Galeri",
  SAVE:         "Simpan Aset",
  UPDATE:       "Perbarui Aset",
  EMPTY:        "Belum ada aset tercatat",
  CONDITIONS: {
    baru:          "Baru",
    baik:          "Baik",
    perlu_servis:  "Perlu Servis",
    rusak:         "Rusak",
  },
};

export const RECURRING = {
  TITLE:               "Transaksi Rutin",
  TOTAL:               "Total",
  ACTIVE:              "Aktif",
  DUE:                 "Jatuh Tempo",
  ADD_NEW:             "Tambah Jadwal",
  EDIT:                "Ubah Jadwal",
  NOTE_LABEL:          "Catatan",
  NOTE_HINT:           "Cth: Gaji, Cicilan, Netflix",
  AMOUNT:              "Nominal",
  AMOUNT_HINT:         "5jt, 500k...",
  CATEGORY:            "Kategori",
  CAT_HINT:            "Gaji, Tagihan...",
  FREQ:                "Frekuensi",
  NEXT_DATE:           "Jadwal Berikutnya",
  FIRST_DATE:          "Jadwal Pertama / Berikutnya",
  STATUS:              "Status",
  RUN_NOW:             "Jalankan",
  ACTIVATE:            "Aktifkan",
  DEACTIVATE:          "Nonaktifkan",
  INACTIVE:            "Nonaktif",
  SAVE:                "Simpan Jadwal",
  UPDATE:              "Perbarui Jadwal",
  SAVE_CHANGES:        "Simpan Perubahan",
  EDIT_TITLE:          "Edit Transaksi Rutin",
  EXPENSE_TYPE:        "Pengeluaran",
  INCOME_TYPE:         "Pemasukan",
  EMPTY:               "Belum ada transaksi rutin",
  DUE_ALERT:           (n) => `${n} transaksi rutin jatuh tempo`,
  DUE_ALERT_TITLE:     "Perlu Dijalankan",
  DUE_ALERT_DESC:      (n) => `${n} transaksi rutin sudah jatuh tempo. Klik "Jalankan" untuk mencatat.`,
  FREQ_DAILY:          "Harian",
  FREQ_WEEKLY:         "Mingguan",
  FREQ_MONTHLY:        "Bulanan",
  EVERY_DAY:           "Setiap hari",
  EVERY_WEEK:          "Setiap 7 hari",
  EVERY_MONTH:         "Setiap bulan",
  OVERDUE:             "Terlambat",
  TODAY:               "Hari ini",
  TOMORROW:            "Besok",
  DAYS_LEFT:           (n) => `${n} hari lagi`,
  ADDED:               "Transaksi rutin ditambahkan!",
  RUN_OK:              (note) => `Transaksi "${note}" berhasil dicatat!`,
  DELETED:             "Dihapus.",
  FAIL_PREFIX:         "Gagal: ",
  VALIDATION_REQUIRED: "Catatan, nominal, dan kategori wajib diisi.",
  VALIDATION_AMOUNT:   "Nominal harus lebih dari 0.",
  DELETE_TITLE:        "Hapus Jadwal?",
  DELETE_MSG:          (note) => `${note} akan dihapus permanen.`,
};

export const MORE = {
  TITLE:         "Lainnya",
  EXPORT:        "Ekspor Laporan",
  EXPORT_SUB:    "Unduh data ke file Excel",
  USER_MGMT:     "Manajemen Pengguna",
  USER_MGMT_SUB: "Kelola akun pengguna (Admin)",
  ADMIN_LABEL:   "Administrator",
  PANDUAN:       "Panduan",
  PANDUAN_SUB:   "Cara penggunaan lengkap",
  ABOUT:         "Tentang Aplikasi",
  ABOUT_SUB:     `Versi ${APP_VERSION}`,
  LANGUAGE:      "Bahasa",
  LANGUAGE_SUB:  "Ganti bahasa tampilan",
  LOGOUT:        "Keluar dari Akun",
  LOGOUT_SHORT:  "Keluar",
  LOGOUT_YES:    "Ya, Keluar",
  BY_AUTHOR:     `dibuat dengan ♥ oleh ${APP_AUTHOR}`,
};

export const ABOUT = {
  TITLE:   "Tentang ArtaKita",
  VERSION: `Versi ${APP_VERSION}`,
  DESC:    "Aplikasi manajemen keuangan pribadi & bersama yang cerdas, cepat, dan aman.",
  FEATURES:"Fitur Utama",
  FEATURE_LIST: [
    "Pencatatan transaksi cerdas",
    "Manajemen hutang & piutang",
    "Pelacakan aset",
    "Transaksi rutin otomatis",
    "Statistik & alokasi anggaran",
    "Berbagi dompet bersama",
    "Mode offline dengan sinkronisasi",
  ],
  TECH:    "Dibangun dengan Next.js, Supabase & ♥",
  BY:      `by ${APP_AUTHOR}`,
};

export const FORM = {
  SAVE:         "Simpan",
  CANCEL:       "Batal",
  EDIT:         "Ubah",
  DELETE:       "Hapus",
  ADD:          "Tambah",
  CLOSE:        "Tutup",
  PROCESSING:   "Memproses...",
  SAVING:       "Menyimpan...",
  UPLOADING:    "Mengupload...",
  LOADING:      "Memuat...",
  LOADING_DATA: "Memuat data...",
  SAVE_CHANGES: "Simpan Perubahan",
};

export const LOGIN = {
  TITLE:          APP_NAME,
  TAGLINE:        APP_TAGLINE,
  USERNAME_LABEL: "Username / Email",
  USERNAME_HINT:  "Masukkan username atau email",
  PASSWORD_LABEL: "Kata Sandi",
  PASSWORD_HINT:  "••••••••",
  SUBMIT:         "Masuk",
  LOADING:        "Memproses...",
  WRONG_PASS:     (r) => `Kata sandi salah! (Sisa percobaan: ${r})`,
  LOCKED:         "Akses dibekukan. Tunggu 30 detik.",
  FORCE_TITLE:    "Ganti Kata Sandi",
  FORCE_DESC:     "Demi keamanan, ganti kata sandi default sebelum melanjutkan.",
  NEW_PASS_HINT:  "Masukkan Kata Sandi Baru",
  FORCE_SUBMIT:   "Simpan & Lanjutkan",
};

export const TOAST = {
  TRX_ADDED:    "Transaksi berhasil dicatat! ✨",
  TRX_UPDATED:  "Transaksi berhasil diperbarui!",
  TRX_DELETED:  "Transaksi dihapus.",
  EXPORT_OK:    "Laporan berhasil diunduh!",
  OFFLINE:      "Tidak ada koneksi internet",
  SYNCED:       (n) => `${n} transaksi berhasil disinkronkan!`,
  ERROR:        "Terjadi kesalahan. Coba lagi.",
  FORMAT_ERROR: "Format salah! Cth: 50k makan siang",
  FAIL_PREFIX:  "Gagal: ",
};

export const CONFIRM = {
  DELETE_TRX:       "Hapus transaksi ini secara permanen?",
  DELETE_TRX_TITLE: "Hapus Transaksi?",
  CANT_UNDO:        "Tindakan ini tidak dapat dibatalkan.",
  DELETE_BTN:       "Hapus",
  CANCEL_BTN:       "Batal",
};

export const CMD = {
  HINT:          "Cth: 50k makan siang  |  in 5jt gaji",
  INCOME_PREFIX: "in",
};

export const LANG = {
  TITLE:      "Bahasa",
  ID:         "Indonesia",
  EN:         "English",
  CHANGE_MSG: "Bahasa berhasil diubah!",
};

export const SAVINGS = {
  TITLE:            "Celengan & Target",
  SECTION_LABEL:    "Target Impian",
  ADD_GOAL:         "+ Target",
  SAVE_GOAL:        "Simpan Target",
  GOAL_NAME_HINT:   "Nama target (Cth: Laptop, Dana Darurat)",
  GOAL_TARGET_HINT: "Target (Cth: 5jt)",
  GOAL_INIT_HINT:   "Isi awal (opsional)",
  MUTASI:           "Mutasi Saldo",
  ADD_BTN:          "+ Tabung",
  USE_BTN:          "- Pakai",
  AMOUNT_HINT:      "Nominal (Cth: 10k, 50k)",
  EMPTY:            "Belum Ada Target",
  INVALID_AMOUNT:   "Masukkan nominal yang valid",
  DELETE_TITLE:     "Hapus Target?",
  DELETE_MSG:       "Target ini dan seluruh progresnya akan dihapus permanen.",
  DELETE_BTN:       "Hapus Target",
};

export const GUIDE = {
  PAGE_TITLE:        "Panduan Pengguna",
  PAGE_SUBTITLE:     "Panduan lengkap semua fitur aplikasi",
  QUICK_START_TITLE: "Mulai Cepat",
  QUICK_START_A:     "50k makan siang",
  QUICK_START_B:     "in 5jt gaji",
  QUICK_START_TEXT:  (a, b) => `Ketik ${a} di kolom bawah untuk catat pengeluaran, atau ${b} untuk pemasukan.`,
  TOPICS:            (n) => `${n} topik`,
  SECTIONS: {
    mulai: {
      title: "Memulai ArtaKita",
      items: [
        { q: "Apa itu ArtaKita?", a: "ArtaKita adalah aplikasi catatan keuangan pribadi dan bersama. Kamu bisa catat pengeluaran & pemasukan harian, lacak hutang, kelola aset, buat target tabungan, dan lihat analisis keuangan — semua dalam satu tempat." },
        { q: "Cara login pertama kali", a: "Minta username dan password sementara dari admin. Saat pertama login, kamu akan diminta ganti password. Masukkan username saja (tanpa @) atau email lengkap." },
        { q: "4 tab utama di aplikasi ini", a: "• Beranda — Saldo & daftar transaksi harian\n• Statistik — Grafik pengeluaran & batas anggaran\n• Keuangan — Hutang, cicilan rutin, aset, celengan & kategori\n• Lainnya — Ekspor laporan, panduan & pengaturan" },
      ],
    },
    beranda: {
      title: "Tab Beranda",
      items: [
        { q: "Melihat saldo & transaksi", a: "Halaman utama menampilkan total saldo dompet aktif, pemasukan & pengeluaran bulan ini, dan daftar transaksi terbaru." },
        { q: "Cara catat transaksi cepat", a: "Gunakan kolom input di bagian bawah. Ketik:\n• Pengeluaran: 50k makan siang\n• Pemasukan: in 5jt gaji\n• Dengan kategori: 50k makan pos Makanan\n\nFormat nominal yang bisa dipakai: 50k, 500rb, 1jt, 1.5jt, 500ribu, atau angka biasa." },
        { q: "Filter & cari transaksi", a: "• Ketik di kotak pencarian untuk cari berdasarkan nama atau kategori\n• Tap pill kategori untuk filter kategori tertentu\n• Tap Hari Ini / 7 Hari / Bulan Ini untuk filter waktu cepat\n• Tap 'Pilih Tanggal' untuk filter rentang tanggal sendiri" },
        { q: "Ganti dompet aktif", a: "Tap icon dompet di pojok kanan atas. Daftar dompet akan muncul. Tap nama dompet untuk mengaktifkannya." },
        { q: "Mode gelap & terang", a: "Tap icon bulan atau matahari di pojok kanan atas untuk ganti tampilan gelap atau terang." },
        { q: "Edit atau hapus transaksi", a: "Tap icon pensil pada transaksi untuk edit nominal, catatan, atau kategori. Tap icon tempat sampah untuk hapus. Tap icon mata untuk lihat foto nota (kalau ada)." },
        { q: "Tampilkan transaksi lebih lama", a: "Tap tombol 'Muat Lebih Banyak' di bawah daftar untuk menampilkan transaksi yang lebih lama." },
      ],
    },
    statistik: {
      title: "Tab Statistik",
      items: [
        { q: "Tab Pengeluaran", a: "Menampilkan nilai kesehatan keuangan (grade A–F), total pengeluaran vs pemasukan, dan rincian per kategori dalam bentuk progress bar." },
        { q: "Apa arti grade keuangan?", a: "• A — Pengeluaran di bawah 50% pemasukan (sangat sehat)\n• B — 50–70% pemasukan (bagus)\n• C — 70–90% pemasukan (mulai waspada)\n• D — Di atas 90% pemasukan (perlu perhatian)\n• F — Tidak ada pemasukan sama sekali" },
        { q: "Tab Alokasi Anggaran", a: "Menampilkan semua kategori pengeluaran bulan ini beserta batas anggaran yang sudah diatur. Progress bar berubah warna: hijau (aman), kuning (di atas 50%), merah (di atas 80% atau sudah melebihi)." },
        { q: "Cara atur batas anggaran", a: "Tap icon pensil pada kategori manapun → isi nominal batas → tap 'Simpan Batas'. Tap 'Hapus Batas' kalau mau menghapus limit-nya." },
        { q: "Peringatan alokasi melebihi saldo", a: "Kalau total semua anggaran melebihi saldo dompet, akan muncul peringatan merah di bagian atas tab Alokasi. Sesuaikan batas anggaran agar tidak minus." },
      ],
    },
    keuangan: {
      title: "Tab Keuangan",
      items: [
        { q: "Cara navigasi di Keuangan", a: "Tab Keuangan punya 5 menu: Hutang & Piutang, Transaksi Rutin, Manajemen Aset, Celengan & Target, dan Kategori. Tap salah satu untuk masuk. Tap 'Keuangan' di atas atau tap tab Keuangan di navbar untuk kembali ke daftar menu." },
        { q: "Catat hutang baru", a: "Masuk ke Hutang & Piutang → tap tombol + → pilih tipe Hutang atau Piutang → isi nama, nominal, dan opsional tanggal jatuh tempo → tap Simpan." },
        { q: "Bayar hutang", a: "Tap card hutang untuk buka detail → tap 'Bayar Hutang' → isi nominal pembayaran → tap OK. Pembayaran otomatis tercatat di dompet. Kalau sudah lunas, hutang pindah ke tab Lunas." },
        { q: "Tab Lunas", a: "Menampilkan riwayat hutang atau piutang yang sudah selesai. Tap card untuk lihat detail riwayat pembayaran. Tap 'Hapus Riwayat' untuk menghapus dari daftar." },
        { q: "Urutkan daftar hutang", a: "Tap icon panah atas-bawah di pojok kanan atas → pilih urutan: Nominal Terbesar, Persentase Terbayar, atau Jatuh Tempo Terdekat." },
        { q: "Transaksi Rutin", a: "Untuk pengeluaran atau pemasukan yang terjadi berulang (gaji, cicilan, langganan). Tap + untuk tambah jadwal baru, pilih frekuensi Harian, Mingguan, atau Bulanan. Tap 'Jalankan' untuk mencatat transaksi sekarang." },
        { q: "Manajemen Aset", a: "Catat inventaris barang dengan foto, nama toko, tanggal beli, harga, kondisi, dan catatan. Foto aset bisa dilihat fullscreen dengan fitur zoom." },
        { q: "Celengan & Target", a: "Buat target tabungan dengan nama dan nominal target. Tap 'Mutasi Saldo' untuk tambah atau kurangi saldo tabungan. Progress bar menunjukkan seberapa dekat ke target." },
        { q: "Kelola Kategori", a: "Tambah, edit, atau hapus kategori transaksi sendiri. Kategori yang sudah dipakai di transaksi tidak bisa dihapus." },
      ],
    },
    lainnya: {
      title: "Tab Lainnya",
      items: [
        { q: "Ekspor Laporan", a: "Tap 'Ekspor Laporan' → file Excel otomatis diunduh dengan 5 sheet: Transaksi, Hutang Piutang, Aset, Transaksi Rutin, dan Target. Data diambil dari dompet aktif saat ini." },
        { q: "Ganti bahasa tampilan", a: "Di tab Lainnya, tap toggle ID / EN untuk ganti bahasa antara Indonesia dan Inggris. Perubahan langsung berlaku." },
        { q: "Manajemen Pengguna (Admin)", a: "Hanya terlihat untuk akun admin. Menampilkan semua pengguna aktif. Fitur: tambah user baru, reset password, nonaktifkan atau aktifkan akun, dan hapus akun." },
        { q: "Tentang Aplikasi", a: "Menampilkan versi aplikasi, ringkasan fitur, dan info pengembang." },
        { q: "Keluar dari Akun", a: "Tap 'Keluar dari Akun' → tap 'Ya, Keluar' untuk konfirmasi. Kamu akan kembali ke halaman login." },
      ],
    },
    dompet: {
      title: "Manajemen Dompet",
      items: [
        { q: "Buat dompet baru", a: "Tap icon dompet di header Beranda → tap 'Tambah Rekening Baru' → isi nama → tap 'Buka Rekening'. Dompet baru langsung jadi aktif." },
        { q: "Bagikan dompet ke pengguna lain", a: "Tap icon dompet → tap icon share pada dompet yang ingin dibagikan → pilih pengguna → tap 'Bagikan Akses Sekarang'. Pengguna yang dipilih bisa melihat dan mencatat transaksi di dompet itu." },
        { q: "Ubah nama dompet", a: "Tap icon dompet → tap icon pensil pada dompet → ketik nama baru → tap centang atau tekan Enter." },
        { q: "Dompet yang dibagikan", a: "• Pemilik: header menampilkan 'Dibagikan ke @username'\n• Penerima: header menampilkan 'Dibagikan oleh @username'\nKeduanya bisa mencatat transaksi di dompet bersama." },
      ],
    },
    offline: {
      title: "Mode Offline",
      items: [
        { q: "Bisa dipakai tanpa internet?", a: "Iya, bisa. Kalau internet mati, transaksi yang kamu catat tersimpan sementara di HP. Strip kuning akan muncul di kartu saldo. Begitu internet nyambung lagi, semua data otomatis dikirim ke server." },
        { q: "Status sinkronisasi", a: "• Strip kuning: offline, transaksi menunggu dikirim\n• Strip biru berkedip: sedang mengirim data\n• Strip hilang: semua sudah tersimpan\n\nTransaksi yang belum terkirim ditandai badge 'Menunggu'." },
        { q: "Data apa yang bisa dilihat saat offline?", a: "100 transaksi terakhir tersimpan di HP dan bisa dilihat tanpa internet. Data lain seperti hutang dan aset perlu koneksi internet." },
      ],
    },
    tips: {
      title: "Tips & Trik",
      items: [
        { q: "Cara tercepat catat transaksi", a: "Pakai kolom input di bawah:\n• '50k makan siang' → langsung tercatat sebagai pengeluaran\n• 'in 5jt gaji' → pemasukan Gaji\n• '200k belanja pos Kebutuhan' → kategori Kebutuhan dibuat otomatis\n\nAplikasi belajar dari pola kamu dan akan auto-isi kategori lama-kelamaan." },
        { q: "Format nominal yang bisa dipakai", a: "50k = Rp 50.000\n500rb = Rp 500.000\n1jt = Rp 1.000.000\n1.5jt = Rp 1.500.000\n500ribu = Rp 500.000\nAngka biasa juga bisa: 50000" },
        { q: "Foto nota transaksi", a: "Saat edit transaksi, kamu bisa pasang foto nota atau struk. Foto otomatis dikecilkan agar tidak terlalu besar. Tap icon mata di card transaksi untuk lihat foto fullscreen." },
        { q: "Atur batas anggaran bulanan", a: "Masuk ke tab Statistik → tap Alokasi → tap pensil pada kategori → atur batas. Progress bar akan merah kalau pengeluaran mendekati atau melebihi batas." },
        { q: "Backup data", a: "Data tersimpan otomatis di cloud. Untuk backup manual, gunakan fitur Ekspor Laporan di tab Lainnya — download file Excel sebagai salinan." },
      ],
    },
  },
};
