// ============================================================
// ARTAKITA — ENGLISH
// ============================================================

export const APP_NAME    = "ArtaKita";
export const APP_TAGLINE = "My Finance, Your Finance";
export const APP_VERSION = "2.0.0";
export const APP_AUTHOR  = "MIH";

export const NAV = {
  HOME:    "Home",
  STATS:   "Stats",
  FINANCE: "Finance",
  MORE:    "More",
};

export const HOME = {
  TOTAL_BALANCE:  "Total Balance",
  CIRCULATION:    "Current Flow",
  INCOME:         "Income",
  EXPENSE:        "Expense",
  ACTIVITY_LOG:   "Activity Log",
  SEARCH_HINT:    "Search transactions...",
  EMPTY:          "No transactions yet",
  LOAD_MORE:      "Load More",
  LOADING:        "Loading...",
  FILTER_TODAY:   "Today",
  FILTER_WEEK:    "7 Days",
  FILTER_MONTH:   "This Month",
  FILTER_CUSTOM:  "Pick Date",
  ALL_CATEGORIES: "All",
  DATE_FROM:      "From Date",
  DATE_TO:        "To Date",
  OFFLINE_MSG:    "Offline — transactions will sync when online",
  SYNCING_MSG:    (n) => `Syncing ${n} transactions...`,
  PENDING_MSG:    (n) => `${n} transactions pending sync`,
};

export const WALLET = {
  TITLE:       "Wallet",
  PERSONAL:    "Personal Wallet",
  SHARED_WITH: (u) => `Shared with @${u}`,
  SHARED_BY:   (u) => `Shared by @${u}`,
  ACTIVE:      "Active",
  ADD_NEW:     "Add New Wallet",
  NAME_LABEL:  "Wallet Name",
  NAME_HINT:   "E.g.: Main Account",
  SAVE:        "Save",
  OPEN:        "Open Wallet",
  SETUP_TITLE: "Create Your First Wallet",
  SETUP_DESC:  "Welcome! Create a wallet to start tracking your finances.",
  CREATE:      "Create Wallet",
};

export const STATS = {
  TITLE:          "Statistics",
  TAB_EXPENSE:    "Expenses",
  TAB_ALLOCATION: "Allocation",
  TOTAL_EXPENSE:  "Total Expenses",
  TOTAL_INCOME:   "Income",
  CATEGORY_DETAIL:"Category Breakdown",
  ALLOCATION:     "Budget Allocation",
  SET_LIMIT:      "Set Limit",
  LIMIT_LABEL:    "Budget Limit",
  LIMIT_HINT:     "E.g.: 500k, 1m",
  DELETE_LIMIT:   "Remove Limit",
  SAVE_LIMIT:     "Save Limit",
  USED_THIS_MONTH:"Used this month",
  CURRENT_LIMIT:  "Current limit",
  REMAINING:      "Remaining",
  OVER_LIMIT:     "Over Budget!",
  NOT_SET:        "Not set",
  WARNING_OVER:   "Total allocation exceeds balance. Adjust your budget limits.",
  AFTER_ALLOC:    "Balance after allocation",
  HEALTH_TITLE:   "Financial Health",
  NO_DATA:        "No data this month",
  GRADE: {
    A: "Excellent! Your cash surplus is safe.",
    B: "Good. Your finances are stable this month.",
    C: "Warning. Reduce unnecessary spending.",
    D: "Danger! Expenses nearly exceed income.",
    F: "Deficit! No income recorded yet.",
    "-": "No transactions this month.",
  },
};

export const FINANCE = {
  TITLE:          "Finance",
  DEBTS:          "Debts & Receivables",
  RECURRING:      "Recurring Transactions",
  ASSETS:         "Asset Management",
  CATEGORIES:     "Categories",
  SAVINGS:        "Savings & Goals",
  DEBTS_SUB:      "Track debts & receivables",
  RECURRING_SUB:  "Scheduled recurring transactions",
  ASSETS_SUB:     "Inventory of goods & property",
  CATEGORIES_SUB: "Manage transaction categories",
  SAVINGS_SUB:    "Savings & dream goals",
};

export const DEBT = {
  TITLE:        "Debts & Receivables",
  TAB_DEBT:     "Debts",
  TAB_RECEIVE:  "Receivables",
  TAB_PAID:     "Settled",
  TOTAL_DEBT:   "Total Debt",
  TOTAL_REC:    "Total Receivable",
  SORT:         "Sort By",
  SORT_NOMINAL: "Largest Amount",
  SORT_PERCENT: "Most Paid",
  SORT_DUEDATE: "Nearest Due Date",
  ADD_NEW:      "New Record",
  PERSON_NAME:  "Name",
  PERSON_HINT:  "E.g.: John, Jane",
  NOMINAL:      "Amount",
  NOMINAL_HINT: "E.g.: 500k, 1m",
  DUE_DATE:     "Due Date",
  PAY_DEBT:     "Pay Debt",
  RECEIVE:      "Receive Payment",
  CANCEL:       "Cancel",
  EDIT:         "Edit",
  DELETE:       "Delete",
  SAVE:         "Save",
  PAID_BADGE:   "Settled",
  PAID_PERCENT: "Paid",
  REMAINING:    "Remaining",
  PAYMENT_HISTORY: "Payment History",
  EMPTY_DEBT:   "No debt records",
  EMPTY_REC:    "No receivable records",
  EMPTY_PAID:   "Nothing settled yet",
  SAVE_DEBT:    "Save Debt",
  SAVE_REC:     "Save Receivable",
  WALLET_BALANCE: "Wallet balance",
  EXCEED_DEBT:  (v) => `Exceeds remaining debt: Rp ${v}`,
  EXCEED_BAL:   (v) => `Insufficient balance! Balance: Rp ${v}`,
  EXCEED_ZERO:  "Amount must be greater than 0",
};

export const ASSET = {
  TITLE:        "Asset Management",
  TOTAL_ASSETS: "Total Assets",
  TOTAL_VALUE:  "Estimated Value",
  ITEMS:        "items recorded",
  ADD_NEW:      "Add Asset",
  EDIT:         "Edit Asset",
  NAME_LABEL:   "Item Name",
  NAME_HINT:    "E.g.: Dell Laptop, iPhone 15",
  STORE_LABEL:  "Store Name",
  STORE_HINT:   "Amazon, Apple Store...",
  DATE_LABEL:   "Purchase Date",
  PRICE_LABEL:  "Purchase Price",
  PRICE_HINT:   "E.g.: 5m, 500k",
  CONDITION:    "Condition",
  NOTES_LABEL:  "Notes",
  NOTES_HINT:   "Serial number, warranty...",
  PHOTO:        "Asset Photo",
  CAMERA:       "Camera / Gallery",
  SAVE:         "Save Asset",
  UPDATE:       "Update Asset",
  EMPTY:        "No assets recorded",
  CONDITIONS: {
    baru:          "New",
    baik:          "Good",
    perlu_servis:  "Needs Service",
    rusak:         "Damaged",
  },
};

export const RECURRING = {
  TITLE:               "Recurring Transactions",
  TOTAL:               "Total",
  ACTIVE:              "Active",
  DUE:                 "Due",
  ADD_NEW:             "Add Schedule",
  EDIT:                "Edit Schedule",
  NOTE_LABEL:          "Note",
  NOTE_HINT:           "E.g.: Salary, Netflix",
  AMOUNT:              "Amount",
  AMOUNT_HINT:         "5m, 500k...",
  CATEGORY:            "Category",
  CAT_HINT:            "Salary, Bills...",
  FREQ:                "Frequency",
  NEXT_DATE:           "Next Schedule",
  FIRST_DATE:          "First / Next Date",
  STATUS:              "Status",
  RUN_NOW:             "Run Now",
  ACTIVATE:            "Activate",
  DEACTIVATE:          "Deactivate",
  INACTIVE:            "Inactive",
  SAVE:                "Save Schedule",
  UPDATE:              "Update Schedule",
  SAVE_CHANGES:        "Save Changes",
  EDIT_TITLE:          "Edit Recurring Transaction",
  EXPENSE_TYPE:        "Expense",
  INCOME_TYPE:         "Income",
  EMPTY:               "No recurring transactions",
  DUE_ALERT:           (n) => `${n} recurring transactions due`,
  DUE_ALERT_TITLE:     "Action Required",
  DUE_ALERT_DESC:      (n) => `${n} recurring transactions due. Click "Run Now" to record.`,
  FREQ_DAILY:          "Daily",
  FREQ_WEEKLY:         "Weekly",
  FREQ_MONTHLY:        "Monthly",
  EVERY_DAY:           "Every day",
  EVERY_WEEK:          "Every 7 days",
  EVERY_MONTH:         "Every month",
  OVERDUE:             "Overdue",
  TODAY:               "Today",
  TOMORROW:            "Tomorrow",
  DAYS_LEFT:           (n) => `${n} days left`,
  ADDED:               "Recurring transaction added!",
  RUN_OK:              (note) => `"${note}" recorded!`,
  DELETED:             "Deleted.",
  FAIL_PREFIX:         "Failed: ",
  VALIDATION_REQUIRED: "Note, amount, and category are required.",
  VALIDATION_AMOUNT:   "Amount must be greater than 0.",
  DELETE_TITLE:        "Delete Schedule?",
  DELETE_MSG:          (note) => `${note} will be permanently deleted.`,
};

export const MORE = {
  TITLE:         "More",
  EXPORT:        "Export Report",
  EXPORT_SUB:    "Download data to Excel file",
  USER_MGMT:     "User Management",
  USER_MGMT_SUB: "Manage user accounts (Admin)",
  ADMIN_LABEL:   "Administrator",
  PANDUAN:       "Guide",
  PANDUAN_SUB:   "Complete usage guide",
  ABOUT:         "About App",
  ABOUT_SUB:     `Version ${APP_VERSION}`,
  LANGUAGE:      "Language",
  LANGUAGE_SUB:  "Change display language",
  LOGOUT:        "Sign Out",
  LOGOUT_SHORT:  "Sign Out",
  LOGOUT_YES:    "Yes, Sign Out",
  BY_AUTHOR:     `made with ♥ by ${APP_AUTHOR}`,
};

export const ABOUT = {
  TITLE:   "About ArtaKita",
  VERSION: `Version ${APP_VERSION}`,
  DESC:    "A smart, fast, and secure personal & shared finance management app.",
  FEATURES:"Key Features",
  FEATURE_LIST: [
    "Smart transaction recording",
    "Debt & receivable management",
    "Asset tracking",
    "Automatic recurring transactions",
    "Statistics & budget allocation",
    "Shared wallet collaboration",
    "Offline mode with sync",
  ],
  TECH:    "Built with Next.js, Supabase & ♥",
  BY:      `by ${APP_AUTHOR}`,
};

export const FORM = {
  SAVE:         "Save",
  CANCEL:       "Cancel",
  EDIT:         "Edit",
  DELETE:       "Delete",
  ADD:          "Add",
  CLOSE:        "Close",
  PROCESSING:   "Processing...",
  SAVING:       "Saving...",
  UPLOADING:    "Uploading...",
  LOADING:      "Loading...",
  LOADING_DATA: "Loading data...",
  SAVE_CHANGES: "Save Changes",
};

export const LOGIN = {
  TITLE:          APP_NAME,
  TAGLINE:        APP_TAGLINE,
  USERNAME_LABEL: "Username / Email",
  USERNAME_HINT:  "Enter username or email",
  PASSWORD_LABEL: "Password",
  PASSWORD_HINT:  "••••••••",
  SUBMIT:         "Sign In",
  LOADING:        "Processing...",
  WRONG_PASS:     (r) => `Wrong password! (${r} attempts left)`,
  LOCKED:         "Access locked. Wait 30 seconds.",
  FORCE_TITLE:    "Change Password",
  FORCE_DESC:     "For security, change your default password before continuing.",
  NEW_PASS_HINT:  "Enter New Password",
  FORCE_SUBMIT:   "Save & Continue",
};

export const TOAST = {
  TRX_ADDED:    "Transaction recorded! ✨",
  TRX_UPDATED:  "Transaction updated!",
  TRX_DELETED:  "Transaction deleted.",
  EXPORT_OK:    "Report downloaded!",
  OFFLINE:      "No internet connection",
  SYNCED:       (n) => `${n} transactions synced!`,
  ERROR:        "Something went wrong. Try again.",
  FORMAT_ERROR: "Wrong format! E.g.: 50k lunch",
  FAIL_PREFIX:  "Failed: ",
};

export const CONFIRM = {
  DELETE_TRX:       "Permanently delete this transaction?",
  DELETE_TRX_TITLE: "Delete Transaction?",
  CANT_UNDO:        "This action cannot be undone.",
  DELETE_BTN:       "Delete",
  CANCEL_BTN:       "Cancel",
};

export const CMD = {
  HINT:          "E.g.: 50k lunch  |  in 5m salary",
  INCOME_PREFIX: "in",
};

export const LANG = {
  TITLE:      "Language",
  ID:         "Indonesia",
  EN:         "English",
  CHANGE_MSG: "Language changed!",
};

export const SAVINGS = {
  TITLE:            "Savings & Goals",
  SECTION_LABEL:    "Dream Goals",
  ADD_GOAL:         "+ Goal",
  SAVE_GOAL:        "Save Goal",
  GOAL_NAME_HINT:   "Goal name (E.g.: Laptop, Emergency Fund)",
  GOAL_TARGET_HINT: "Target (E.g.: 5m)",
  GOAL_INIT_HINT:   "Initial amount (optional)",
  MUTASI:           "Adjust Balance",
  ADD_BTN:          "+ Add",
  USE_BTN:          "- Withdraw",
  AMOUNT_HINT:      "Amount (E.g.: 10k, 50k)",
  EMPTY:            "No Goals Yet",
  INVALID_AMOUNT:   "Enter a valid amount",
  DELETE_TITLE:     "Delete Goal?",
  DELETE_MSG:       "This goal and all its progress will be permanently deleted.",
  DELETE_BTN:       "Delete Goal",
};

export const GUIDE = {
  PAGE_TITLE:        "User Guide",
  PAGE_SUBTITLE:     "Complete guide to all app features",
  QUICK_START_TITLE: "Quick Start",
  QUICK_START_A:     "50k lunch",
  QUICK_START_B:     "in 5m salary",
  QUICK_START_TEXT:  (a, b) => `Type ${a} in the bar below to record an expense, or ${b} for income.`,
  TOPICS:            (n) => `${n} topics`,
  SECTIONS: {
    mulai: {
      title: "Getting Started",
      items: [
        { q: "What is ArtaKita?", a: "ArtaKita is a personal and shared finance tracking app. You can record daily income & expenses, track debts, manage assets, set savings goals, and view spending analysis — all in one place." },
        { q: "How to log in for the first time", a: "Ask the admin for a temporary username and password. On your first login, you'll be asked to change your password. Enter just the username (without @) or a full email address." },
        { q: "The 4 main tabs", a: "• Home — Balance & daily transaction list\n• Stats — Spending charts & budget limits\n• Finance — Debts, recurring transactions, assets, savings & categories\n• More — Export reports, guide & settings" },
      ],
    },
    beranda: {
      title: "Home Tab",
      items: [
        { q: "Viewing balance & transactions", a: "The main page shows your active wallet's total balance, this month's income & expenses, and the latest transactions." },
        { q: "How to quickly record a transaction", a: "Use the input bar at the bottom. Type:\n• Expense: 50k lunch\n• Income: in 5m salary\n• With category: 50k lunch pos Food\n\nSupported formats: 50k, 500k, 1m, 1.5m, or plain numbers." },
        { q: "Filter & search transactions", a: "• Type in the search box to find by name or category\n• Tap a category pill to filter a specific category\n• Tap Today / 7 Days / This Month for quick time filters\n• Tap 'Pick Date' for a custom date range" },
        { q: "Switch active wallet", a: "Tap the wallet icon in the top right corner. A list of wallets will appear. Tap a wallet name to activate it." },
        { q: "Dark & light mode", a: "Tap the moon or sun icon in the top right header to switch between dark and light mode." },
        { q: "Edit or delete a transaction", a: "Tap the pencil icon on a transaction to edit the amount, note, or category. Tap the trash icon to delete. Tap the eye icon to view the receipt photo (if any)." },
        { q: "Show older transactions", a: "Tap the 'Load More' button at the bottom of the list to show older transactions." },
      ],
    },
    statistik: {
      title: "Stats Tab",
      items: [
        { q: "Expenses tab", a: "Shows your financial health score (grade A–F), total expenses vs income, and a breakdown by category as progress bars." },
        { q: "What do the financial grades mean?", a: "• A — Expenses below 50% of income (very healthy)\n• B — 50–70% of income (good)\n• C — 70–90% of income (watch out)\n• D — Above 90% of income (needs attention)\n• F — No income recorded at all" },
        { q: "Budget Allocation tab", a: "Shows all spending categories this month along with your set budget limits. Progress bars change color: green (safe), yellow (above 50%), red (above 80% or over budget)." },
        { q: "How to set a budget limit", a: "Tap the pencil icon on any category → enter the limit amount → tap 'Save Limit'. Tap 'Remove Limit' to clear it." },
        { q: "Allocation exceeds balance warning", a: "If your total budget allocation exceeds the wallet balance, a red warning appears at the top of the Allocation tab. Adjust your limits to stay in balance." },
      ],
    },
    keuangan: {
      title: "Finance Tab",
      items: [
        { q: "How to navigate Finance", a: "The Finance tab has 5 menus: Debts & Receivables, Recurring Transactions, Asset Management, Savings & Goals, and Categories. Tap one to enter. Tap 'Finance' at the top or tap the Finance tab in the navbar to go back." },
        { q: "Record a new debt", a: "Go to Debts & Receivables → tap the + button → choose Debt or Receivable → enter name, amount, and optional due date → tap Save." },
        { q: "Pay off a debt", a: "Tap a debt card to expand → tap 'Pay Debt' → enter the payment amount → tap OK. The payment is automatically recorded in your wallet. Once fully paid, the debt moves to the Settled tab." },
        { q: "Settled tab", a: "Shows the history of settled debts or receivables. Tap a card to see payment history. Tap 'Delete Record' to remove it from the list." },
        { q: "Sort the debt list", a: "Tap the sort icon in the top right → choose: Largest Amount, Most Paid, or Nearest Due Date." },
        { q: "Recurring Transactions", a: "For regular income or expenses (salary, installments, subscriptions). Tap + to add a new schedule, choose Daily, Weekly, or Monthly. Tap 'Run Now' to record the transaction immediately." },
        { q: "Asset Management", a: "Record an inventory of items with photos, store name, purchase date, price, condition, and notes. Asset photos can be viewed fullscreen with zoom." },
        { q: "Savings & Goals", a: "Create savings targets with a name and target amount. Tap 'Adjust Balance' to add or withdraw. The progress bar shows how close you are to the target." },
        { q: "Manage Categories", a: "Add, edit, or delete custom transaction categories. Categories already used in transactions cannot be deleted." },
      ],
    },
    lainnya: {
      title: "More Tab",
      items: [
        { q: "Export Report", a: "Tap 'Export Report' → an Excel file is automatically downloaded with 5 sheets: Transactions, Debts, Assets, Recurring Transactions, and Goals. Data is from your active wallet." },
        { q: "Change display language", a: "In the More tab, tap the ID / EN toggle to switch between Indonesian and English. The change takes effect immediately." },
        { q: "User Management (Admin)", a: "Only visible to admin accounts. Shows all active users. Features: add new user, reset password, deactivate or activate account, and delete account." },
        { q: "About App", a: "Shows the app version, feature summary, and developer info." },
        { q: "Sign Out", a: "Tap 'Sign Out' → tap 'Yes, Sign Out' to confirm. You'll be returned to the login page." },
      ],
    },
    dompet: {
      title: "Wallet Management",
      items: [
        { q: "Create a new wallet", a: "Tap the wallet icon in the Home header → tap 'Add New Wallet' → enter a name → tap 'Open Wallet'. The new wallet becomes active immediately." },
        { q: "Share a wallet with another user", a: "Tap the wallet icon → tap the share icon on the wallet → select a user → tap 'Share Access Now'. The selected user can view and record transactions in that wallet." },
        { q: "Rename a wallet", a: "Tap the wallet icon → tap the pencil icon on the wallet → type a new name → tap the checkmark or press Enter." },
        { q: "Shared wallets", a: "• Owner: header shows 'Shared with @username'\n• Recipient: header shows 'Shared by @username'\nBoth can record transactions in the shared wallet." },
      ],
    },
    offline: {
      title: "Offline Mode",
      items: [
        { q: "Can I use it without internet?", a: "Yes. If the internet goes down, transactions you record are saved temporarily on your phone. A yellow strip appears above the balance card. Once the connection returns, all data is automatically sent to the server." },
        { q: "Sync status", a: "• Yellow strip: offline, transactions waiting to be sent\n• Blinking blue strip: sending data\n• Strip gone: all synced\n\nUnsynced transactions are marked with a 'Pending' badge." },
        { q: "What data is available offline?", a: "The last 100 transactions are stored on your phone and can be viewed without internet. Other data like debts and assets requires an internet connection." },
      ],
    },
    tips: {
      title: "Tips & Tricks",
      items: [
        { q: "Fastest way to record a transaction", a: "Use the input bar at the bottom:\n• '50k lunch' → recorded instantly as an expense\n• 'in 5m salary' → Income: Salary\n• '200k shopping pos Needs' → creates the Needs category automatically\n\nThe app learns from your patterns and will auto-fill categories over time." },
        { q: "Supported amount formats", a: "50k = Rp 50,000\n500k = Rp 500,000\n1m = Rp 1,000,000\n1.5m = Rp 1,500,000\nPlain numbers also work: 50000" },
        { q: "Transaction receipt photos", a: "When editing a transaction, you can attach a receipt photo. Photos are automatically compressed. Tap the eye icon on a transaction card to view the photo fullscreen." },
        { q: "Set a monthly budget limit", a: "Go to the Stats tab → tap Allocation → tap the pencil on a category → set a limit. The progress bar turns red when spending approaches or exceeds the limit." },
        { q: "Data backup", a: "Data is automatically saved to the cloud. For a manual backup, use Export Report in the More tab — download an Excel file as a copy." },
      ],
    },
  },
};
